name: Master
channels:
- conda-forge
- pytorch
- nvidia
dependencies:
- python=3.12.12
- numpy
- scipy
- matplotlib
- pillow
- opencv
- tqdm
- psutil
- py-cpuinfo
- pytorch
- torchvision
- pytorch-cuda=12.1
- timm
- scikit-learn
- scikit-image
- jupyterlab
- notebook
- ipykernel
- pip
- pip:
  - shap
  - lime
  - torchcam
  - umap-learn
  - kagglehub
  - -e .